---
- name: CHECK TOKEN=>> Check Access Token
  uri:
    url: 'https://{{north_ip}}:{{north_port}}/controller/dc/v3/tenants'
    method: GET
    validate_certs: False
    return_content: yes
    headers:
      X-ACCESS-TOKEN: "{{token_id}}"
      Accept: application/json
      Content_Type: application/json
    status_code: 200
  register: check_token_result
  ignore_errors: yes

- name: CHECK TOKEN=>> Result of Check 
  debug:
    msg: "Token is expired"
  when: check_token_result.status == 401
