---
- name: LOADSWITCHES=>> Query Switches
  uri:
    url: 'https://{{north_ip}}:{{north_port}}/controller/dc/v3/logicnetwork/switchs'
    method: GET
    validate_certs: False
    return_content: yes
    headers:
      X-ACCESS-TOKEN: "{{token_id}}"
      Accept: application/json
      Content_Type: application/json
    status_code: 200
  register: logicswitches_result
  ignore_errors: yes

- name: LOADSWITCHES=>> Convert JSON to Dict
  set_fact:
    switches_name: "{{ logicswitches_result.json.switch|items2dict(key_name='name', value_name='id') }}"
    switches_id: "{{ logicswitches_result.json.switch|items2dict(key_name='id', value_name='name') }}"
